INSERT INTO role VALUES(1, "ROLE_ADMIN");
INSERT INTO role VALUES(2, "ROLE_USER");

INSERT INTO user VALUES(1, "Frank", "frankie@gmail.com", "Frankie", "$2a$10$U69SsCaSBlI/x4X7WaZrMuTCjHGWwj1DzacR1706zabQlihWaztr.");
INSERT INTO user VALUES(2, "milos@gmail.com", "Milos", "Miki", "$2a$10$U69SsCaSBlI/x4X7WaZrMuTCjHGWwj1DzacR1706zabQlihWaztr.");

INSERT INTO user_role VALUES(1, 1);
INSERT INTO user_role VALUES(2, 2);

INSERT INTO study_program VALUES(1, "IST", "2014");
INSERT INTO study_program VALUES(2, "Management", "2013");

INSERT INTO department VALUES(1, "Artificial Intelligence");
INSERT INTO department VALUES(2, "Software Engineering");
INSERT INTO department VALUES(3, "Economics");
INSERT INTO department VALUES(4, "Business Development");

INSERT INTO course VALUES(null, "Mathematics", "Some goal", "Mandatory", 6, 1, 1);
INSERT INTO course VALUES(null, "Intelligent systems", "Some goal", "Mandatory", 6, 1, 1);
INSERT INTO course VALUES(null, "Advanced Java Technologies", "Some goal", "Optional", 6, 2, 1);
INSERT INTO course VALUES(null, "Java 2", "Some goal", "Mandatory", 6, 2, 2);
INSERT INTO course VALUES(null, "Intro to Programming", "Some goal", "Mandatory", 6, 2, 2);
INSERT INTO course VALUES(null, "Macroeconomics", "Some goal", "Optional", 6, 1, 2);
INSERT INTO course VALUES(null, "Economic indicators", "Some goal", "Optional", 6, 1, 3);
INSERT INTO course VALUES(null, "Market Research", "Some goal", "Mandatory", 6, 2, 3);
INSERT INTO course VALUES(null, "Business Models", "Some goal", "Optional", 6, 2, 3);
INSERT INTO course VALUES(null, "Strategic Management", "Some goal", "Optional", 6, 2, 4);
INSERT INTO course VALUES(null, "Software Patterns", "Some goal", "Mandatory", 6, 1, 4);
INSERT INTO course VALUES(null, "Microeconomics", "Some goal", "Mandatory", 6, 1, 4);
INSERT INTO course VALUES(null, "Data Science", "Some goal", "Optional", 6, 2, 3);

INSERT INTO lecturer VALUES("P", null, "Frank Fransis", "AI", null, "Full Professor", 41, 1);
INSERT INTO lecturer VALUES("P", null, "Anne Bush", "Data science", null, "Associate Professor", 33, 1);
INSERT INTO lecturer VALUES("P", null, "Nicolas Harr", "Functional programming", null, "Full Professor", 40, 2);
INSERT INTO lecturer VALUES("P", null, "Tina Henderson", "User experience", null, "Associate Professor", 41, 2);
INSERT INTO lecturer VALUES("A", null, "Becky Solace", "Linear models", "Masters", null, null, 1);
INSERT INTO lecturer VALUES("A", null, "Frank Sinatra", "NLP", "Bachelor", null, null, 1);
INSERT INTO lecturer VALUES("A", null, "Thomas Moore", "Software architectures", "Masters", null, null, 2);
INSERT INTO lecturer VALUES("A", null, "Samuel L Jackson", "System programming", "Masters", null, null, 2);
INSERT INTO lecturer VALUES("P", null, "Sarah Connor", "Microeconomics", null, "Full Professor", 29, 3);
INSERT INTO lecturer VALUES("P", null, "Michael Moore", "International trade", null, "Associate Professor", 10, 3);
INSERT INTO lecturer VALUES("P", null, "George Clooney", "Business management", null, "Full Professor", 35, 4);
INSERT INTO lecturer VALUES("P", null, "Jessica Marie Fransis", "Technological management", null, "Associate Professor", 15, 4);
INSERT INTO lecturer VALUES("A", null, "Niki Benz", "Economics in politics", "Masters", null, null, 3);
INSERT INTO lecturer VALUES("A", null, "Lidija Savic", "International economics", "Bachelor", null, null, 3);
INSERT INTO lecturer VALUES("A", null, "Jimi Hendrix", "Corporate communication", "Bachelor", null, null, 4);
INSERT INTO lecturer VALUES("A", null, "Tom Cruise", "Market analysis", "Masters", null, null, 4);

INSERT INTO course_unit VALUES(null, "Some description", "Some name", 1, 1);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 2, 1);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 3, 1);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 1, 2);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 2, 2);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 1, 3);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 2, 3);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 3, 3);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 1, 4);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 2, 4);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 1, 5);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 2, 5);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 1, 6);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 2, 6);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 3, 6);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 1, 7);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 1, 8);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 2, 8);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 1, 9);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 2, 9);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 3, 9);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 4, 9);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 1, 10);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 2, 10);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 1, 11);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 1, 12);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 2, 12);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 1, 13);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 2, 13);
INSERT INTO course_unit VALUES(null, "Some description", "Some name", 3, 13);

INSERT INTO course_lecturer VALUES(1, 1);
INSERT INTO course_lecturer VALUES(1, 2);
INSERT INTO course_lecturer VALUES(2, 2);
INSERT INTO course_lecturer VALUES(2, 3);
INSERT INTO course_lecturer VALUES(3, 4);
INSERT INTO course_lecturer VALUES(3, 4);
INSERT INTO course_lecturer VALUES(4, 5);
INSERT INTO course_lecturer VALUES(4, 5);
INSERT INTO course_lecturer VALUES(5, 5);
INSERT INTO course_lecturer VALUES(5, 6);
INSERT INTO course_lecturer VALUES(6, 6);
INSERT INTO course_lecturer VALUES(6, 7);
INSERT INTO course_lecturer VALUES(7, 8);
INSERT INTO course_lecturer VALUES(7, 8);
INSERT INTO course_lecturer VALUES(8, 9);
INSERT INTO course_lecturer VALUES(8, 9);
INSERT INTO course_lecturer VALUES(9, 9);
INSERT INTO course_lecturer VALUES(9, 10);
INSERT INTO course_lecturer VALUES(10, 10);
INSERT INTO course_lecturer VALUES(10, 11);
INSERT INTO course_lecturer VALUES(11, 11);
INSERT INTO course_lecturer VALUES(11, 13);
INSERT INTO course_lecturer VALUES(12, 15);
INSERT INTO course_lecturer VALUES(12, 16);
INSERT INTO course_lecturer VALUES(13, 16);
INSERT INTO course_lecturer VALUES(13, 16);

